[package]
name = "preprocessor"
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "1.1.0"
convert_case = "0.6.0"
itertools = "0.10.5"
rand_core = "0.6.4"
thiserror = "1.0.38"
wyhash = "0.5.0"
